import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/global/Header';
import QueryProvider from '@/providers/QueryProvider';
import AuthProvider from '@/providers/AuthProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '냉시피',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const user = session?.user;
  console.log(session);

  return (
    <html lang='ko'>
      <body className={inter.className}>
        <AuthProvider>
          <QueryProvider>
            <Header user={user} />
            <main className='max-w-screen-2xl w-full mx-auto h-screen -mt-[64px]'>
              <div className='pt-[64px] h-full'>{children}</div>
            </main>
            <div id='portal'></div>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
